# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SdbV1dNaH2OmfRHNFTNHOuJoaLoXq_sc
"""

#BUILDING THE APP
#importing libraries
import sys
import streamlit as st
import pickle
import pandas as pd

# Ensure compatibility with model pickled in older scikit-learn versions
import sklearn
from sklearn.compose import _column_transformer as _ct

if not hasattr(_ct, '_RemainderColsList'):
    # sklearn 1.8 removed _RemainderColsList; add a lightweight compatibility alias
    class _RemainderColsList(list):
        """Compatibility stub for pickled ColumnTransformer state from older sklearn."""
        pass

    _ct._RemainderColsList = _RemainderColsList

# Load the full pipeline
try:
    model = pickle.load(open("california_knn_pipeline.pkl", "rb"))
except Exception as e:
    st.error(
        "Failed to load model pipeline. Ensure scikit-learn is pinned to 1.6.1 or the model is re-saved with your version."
    )
    raise

st.title('California Housing Price Predictor')
st.write('Enter the details below to get a predicted house value.')


#CREATE USER INPUT FIELDS
st.subheader('Property details')
col1, col2 = st.columns(2)
with col1:
    MedInc     = st.number_input('Median Income',      value=3.5)
    HouseAge   = st.number_input('House Age',           value=25.0)
    AveRooms   = st.number_input('Average Rooms',       value=5.2)
    AveBedrms  = st.number_input('Average Bedrooms',    value=1.1)
with col2:
    Population = st.number_input('Population',          value=1200.0)
    AveOccup   = st.number_input('Average Occupancy',   value=2.8)
    Latitude   = st.number_input('Latitude',            value=34.1)
    Longitude  = st.number_input('Longitude',           value=-118.3)

#PREDICTION LOGIC
if st.button('Predict House Value'):
    input_data = pd.DataFrame([[
        MedInc, HouseAge, AveRooms, AveBedrms,
        Population, AveOccup, Latitude, Longitude
    ]], columns=model.feature_names_in_)
    prediction = model.predict(input_data)
    st.success(f"Predicted House Price: ${prediction[0] * 100:.0f},000")

# To run the app, execute from the shell:
# streamlit run app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/california_housing_price_predictor.py
# #BUILDING THE APP
# #importing libraries
# import sys
# # !{sys.executable} -m pip install streamlit # This line should not be in the .py file, install once in notebook
# import streamlit as st
# import pickle
# import pandas as pd
# 
# # Load the full pipeline
# model = pickle.load(open('/content/california_knn_pipeline.pkl', 'rb'))
# st.title('California Housing Price Predictor')
# st.write('Enter the details below to get a predicted house value.')
# 
# #CREATE USER INPUT FIELDS
# st.subheader('Property details')
# col1, col2 = st.columns(2)
# with col1:
#     MedInc     = st.number_input('Median Income',      value=3.5)
#     HouseAge   = st.number_input('House Age',           value=25.0)
#     AveRooms   = st.number_input('Average Rooms',       value=5.2)
#     AveBedrms  = st.number_input('Average Bedrooms',    value=1.1)
# with col2:
#     Population = st.number_input('Population',          value=1200.0)
#     AveOccup   = st.number_input('Average Occupancy',   value=2.8)
#     Latitude   = st.number_input('Latitude',            value=34.1)
#     Longitude  = st.number_input('Longitude',           value=-118.3)
# 
# #PREDICTION LOGIC
# if st.button('Predict House Value'):
#     input_data = pd.DataFrame([[
#         MedInc, HouseAge, AveRooms, AveBedrms,
#         Population, AveOccup, Latitude, Longitude
#     ]], columns=model.feature_names_in_)
#     prediction = model.predict(input_data)
#     st.success(f"Predicted House Price: ${prediction[0] * 100:.0f},000")